# Generated by Django 3.1.3 on 2021-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_part_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(default='Part A', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('Exam_id', 'title'), name='unique_part_exam'),
        ),
    ]
