# Generated by Django 3.1.3 on 2021-01-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210114_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='Exam_id',
            new_name='Exam',
        ),
    ]
