# Generated by Django 3.1.3 on 2021-01-15 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0008_auto_20210115_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='upvotes',
            field=models.ManyToManyField(null=True, related_name='option_upvotes', through='exam.Upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
