# Generated by Django 3.1.3 on 2021-01-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20210115_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='upvotes',
        ),
    ]
