# Generated by Django 3.1.3 on 2021-01-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_option_upvotes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set(),
        ),
    ]
