# Generated by Django 3.1.3 on 2021-01-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210115_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
    ]
