# Generated by Django 3.1.3 on 2021-01-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210115_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='upvotes',
        ),
    ]
